#!/bin/sh
wc -l * | grep "total"
wc -l */* | grep "total"
wc -l */*/* | grep "total"
wc -l */*/*/* | grep "total"
wc -l */*/*/*/* | grep "total"
wc -l */*/*/*/*/* | grep "total"
wc -l */*/*/*/*/*/* | grep "total"
wc -l */*/*/*/*/*/*/* | grep "total"
wc -l */*/*/*/*/*/*/*/* | grep "total"
wc -l */*/*/*/*/*/*/*/*/* | grep "total"
wc -l */*/*/*/*/*/*/*/*/*/* | grep "total"
wc -l */*/*/*/*/*/*/*/*/*/*/* | grep "total"
